arb-dir: lib/l10n
template-arb-file: intl_tr.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
supported-locales:
  - tr # Turkish
  - en # English
  - de # German
  - fr # French
  - es # Spanish
  - ru # Russian
  - it # Italian
  - ar # Arabic
